TARGETS	= $(OBJDIR)chroot $(OBJDIR)clear $(OBJDIR)halt $(OBJDIR)hexdump $(OBJDIR)host $(OBJDIR)hostname $(OBJDIR)ifconfig $(OBJDIR)login $(OBJDIR)mktemp $(OBJDIR)mount $(OBJDIR)poweroff $(OBJDIR)protoid $(OBJDIR)reboot $(OBJDIR)servid $(OBJDIR)tar $(OBJDIR)umount $(OBJDIR)uptime $(OBJDIR)w
OBJDIR	=
PREFIX	= /usr/local
DESTDIR	=
BINDIR	= $(PREFIX)/bin
SBINDIR	= $(PREFIX)/sbin
CC	= cc
CPPFLAGSF=
CPPFLAGS=
CFLAGSF	= -W
CFLAGS	= -Wall -g -O2 -pedantic
RM	= rm -f
LN	= ln -f
MKDIR	= mkdir -m 0755 -p
INSTALL	= install


all: $(TARGETS)

chroot_OBJS = $(OBJDIR)chroot.o
chroot_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
chroot_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)chroot: $(chroot_OBJS)
	$(CC) -o $(OBJDIR)chroot $(chroot_OBJS) $(chroot_LDFLAGS)

clear_OBJS = $(OBJDIR)clear.o
clear_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
clear_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)clear: $(clear_OBJS)
	$(CC) -o $(OBJDIR)clear $(clear_OBJS) $(clear_LDFLAGS)

halt_OBJS = $(OBJDIR)halt.o
halt_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
halt_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)halt: $(halt_OBJS)
	$(CC) -o $(OBJDIR)halt $(halt_OBJS) $(halt_LDFLAGS)

hexdump_OBJS = $(OBJDIR)hexdump.o
hexdump_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
hexdump_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)hexdump: $(hexdump_OBJS)
	$(CC) -o $(OBJDIR)hexdump $(hexdump_OBJS) $(hexdump_LDFLAGS)

host_OBJS = $(OBJDIR)host.o
host_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
host_LDFLAGS = $(LDFLAGSF) $(LDFLAGS) 

$(OBJDIR)host: $(host_OBJS)
	$(CC) -o $(OBJDIR)host $(host_OBJS) $(host_LDFLAGS)

hostname_OBJS = $(OBJDIR)hostname.o
hostname_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
hostname_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)hostname: $(hostname_OBJS)
	$(CC) -o $(OBJDIR)hostname $(hostname_OBJS) $(hostname_LDFLAGS)

ifconfig_OBJS = $(OBJDIR)ifconfig.o
ifconfig_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
ifconfig_LDFLAGS = $(LDFLAGSF) $(LDFLAGS) 

$(OBJDIR)ifconfig: $(ifconfig_OBJS)
	$(CC) -o $(OBJDIR)ifconfig $(ifconfig_OBJS) $(ifconfig_LDFLAGS)

login_OBJS = $(OBJDIR)login.o
login_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
login_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)login: $(login_OBJS)
	$(CC) -o $(OBJDIR)login $(login_OBJS) $(login_LDFLAGS)

mktemp_OBJS = $(OBJDIR)mktemp.o
mktemp_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mktemp_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)mktemp: $(mktemp_OBJS)
	$(CC) -o $(OBJDIR)mktemp $(mktemp_OBJS) $(mktemp_LDFLAGS)

mount_OBJS = $(OBJDIR)mount.o
mount_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
mount_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)mount: $(mount_OBJS)
	$(CC) -o $(OBJDIR)mount $(mount_OBJS) $(mount_LDFLAGS)

poweroff_OBJS = $(OBJDIR)poweroff.o
poweroff_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
poweroff_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)poweroff: $(poweroff_OBJS)
	$(CC) -o $(OBJDIR)poweroff $(poweroff_OBJS) $(poweroff_LDFLAGS)

protoid_OBJS = $(OBJDIR)protoid.o
protoid_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
protoid_LDFLAGS = $(LDFLAGSF) $(LDFLAGS) 

$(OBJDIR)protoid: $(protoid_OBJS)
	$(CC) -o $(OBJDIR)protoid $(protoid_OBJS) $(protoid_LDFLAGS)

reboot_OBJS = $(OBJDIR)reboot.o
reboot_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
reboot_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)reboot: $(reboot_OBJS)
	$(CC) -o $(OBJDIR)reboot $(reboot_OBJS) $(reboot_LDFLAGS)

servid_OBJS = $(OBJDIR)servid.o
servid_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
servid_LDFLAGS = $(LDFLAGSF) $(LDFLAGS) 

$(OBJDIR)servid: $(servid_OBJS)
	$(CC) -o $(OBJDIR)servid $(servid_OBJS) $(servid_LDFLAGS)

tar_OBJS = $(OBJDIR)tar.o
tar_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
tar_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)tar: $(tar_OBJS)
	$(CC) -o $(OBJDIR)tar $(tar_OBJS) $(tar_LDFLAGS)

umount_OBJS = $(OBJDIR)umount.o
umount_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
umount_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)umount: $(umount_OBJS)
	$(CC) -o $(OBJDIR)umount $(umount_OBJS) $(umount_LDFLAGS)

uptime_OBJS = $(OBJDIR)uptime.o
uptime_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
uptime_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)uptime: $(uptime_OBJS)
	$(CC) -o $(OBJDIR)uptime $(uptime_OBJS) $(uptime_LDFLAGS)

w_OBJS = $(OBJDIR)w.o
w_CFLAGS = $(CPPFLAGSF) $(CPPFLAGS) $(CFLAGSF) $(CFLAGS)
w_LDFLAGS = $(LDFLAGSF) $(LDFLAGS)

$(OBJDIR)w: $(w_OBJS)
	$(CC) -o $(OBJDIR)w $(w_OBJS) $(w_LDFLAGS)

$(OBJDIR)chroot.o: chroot.c
	$(CC) $(chroot_CFLAGS) -o $(OBJDIR)chroot.o -c chroot.c

$(OBJDIR)clear.o: clear.c
	$(CC) $(clear_CFLAGS) -o $(OBJDIR)clear.o -c clear.c

$(OBJDIR)halt.o: halt.c
	$(CC) $(halt_CFLAGS) -o $(OBJDIR)halt.o -c halt.c

$(OBJDIR)hexdump.o: hexdump.c
	$(CC) $(hexdump_CFLAGS) -o $(OBJDIR)hexdump.o -c hexdump.c

$(OBJDIR)host.o: host.c
	$(CC) $(host_CFLAGS) -o $(OBJDIR)host.o -c host.c

$(OBJDIR)hostname.o: hostname.c
	$(CC) $(hostname_CFLAGS) -o $(OBJDIR)hostname.o -c hostname.c

$(OBJDIR)ifconfig.o: ifconfig.c
	$(CC) $(ifconfig_CFLAGS) -o $(OBJDIR)ifconfig.o -c ifconfig.c

$(OBJDIR)login.o: login.c
	$(CC) $(login_CFLAGS) -o $(OBJDIR)login.o -c login.c

$(OBJDIR)mktemp.o: mktemp.c
	$(CC) $(mktemp_CFLAGS) -o $(OBJDIR)mktemp.o -c mktemp.c

$(OBJDIR)mount.o: mount.c
	$(CC) $(mount_CFLAGS) -o $(OBJDIR)mount.o -c mount.c

$(OBJDIR)poweroff.o: poweroff.c
	$(CC) $(poweroff_CFLAGS) -o $(OBJDIR)poweroff.o -c poweroff.c

$(OBJDIR)protoid.o: protoid.c
	$(CC) $(protoid_CFLAGS) -o $(OBJDIR)protoid.o -c protoid.c

$(OBJDIR)reboot.o: reboot.c
	$(CC) $(reboot_CFLAGS) -o $(OBJDIR)reboot.o -c reboot.c

$(OBJDIR)servid.o: servid.c
	$(CC) $(servid_CFLAGS) -o $(OBJDIR)servid.o -c servid.c

$(OBJDIR)tar.o: tar.c tar.h
	$(CC) $(tar_CFLAGS) -o $(OBJDIR)tar.o -c tar.c

$(OBJDIR)umount.o: umount.c
	$(CC) $(umount_CFLAGS) -o $(OBJDIR)umount.o -c umount.c

$(OBJDIR)uptime.o: uptime.c utmpx.c
	$(CC) $(uptime_CFLAGS) -o $(OBJDIR)uptime.o -c uptime.c

$(OBJDIR)w.o: w.c utmpx.c
	$(CC) $(w_CFLAGS) -o $(OBJDIR)w.o -c w.c

clean:
	$(RM) -- $(chroot_OBJS) $(clear_OBJS) $(halt_OBJS) $(hexdump_OBJS) $(host_OBJS) $(hostname_OBJS) $(ifconfig_OBJS) $(login_OBJS) $(mktemp_OBJS) $(mount_OBJS) $(poweroff_OBJS) $(protoid_OBJS) $(reboot_OBJS) $(servid_OBJS) $(tar_OBJS) $(umount_OBJS) $(uptime_OBJS) $(w_OBJS)

distclean: clean
	$(RM) -- $(TARGETS)

install: $(TARGETS)
	$(MKDIR) $(DESTDIR)$(SBINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)chroot $(DESTDIR)$(SBINDIR)/chroot
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)clear $(DESTDIR)$(BINDIR)/clear
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)halt $(DESTDIR)$(BINDIR)/halt
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)hexdump $(DESTDIR)$(BINDIR)/hexdump
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)host $(DESTDIR)$(BINDIR)/host
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)hostname $(DESTDIR)$(BINDIR)/hostname
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)ifconfig $(DESTDIR)$(BINDIR)/ifconfig
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)login $(DESTDIR)$(BINDIR)/login
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)mktemp $(DESTDIR)$(BINDIR)/mktemp
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)mount $(DESTDIR)$(BINDIR)/mount
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)poweroff $(DESTDIR)$(BINDIR)/poweroff
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)protoid $(DESTDIR)$(BINDIR)/protoid
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)reboot $(DESTDIR)$(BINDIR)/reboot
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)servid $(DESTDIR)$(BINDIR)/servid
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)tar $(DESTDIR)$(BINDIR)/tar
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)umount $(DESTDIR)$(BINDIR)/umount
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)uptime $(DESTDIR)$(BINDIR)/uptime
	$(MKDIR) $(DESTDIR)$(BINDIR)
	$(INSTALL) -m 0755 $(OBJDIR)w $(DESTDIR)$(BINDIR)/w

uninstall:
	$(RM) -- $(DESTDIR)$(SBINDIR)/chroot
	$(RM) -- $(DESTDIR)$(BINDIR)/clear
	$(RM) -- $(DESTDIR)$(BINDIR)/halt
	$(RM) -- $(DESTDIR)$(BINDIR)/hexdump
	$(RM) -- $(DESTDIR)$(BINDIR)/host
	$(RM) -- $(DESTDIR)$(BINDIR)/hostname
	$(RM) -- $(DESTDIR)$(BINDIR)/ifconfig
	$(RM) -- $(DESTDIR)$(BINDIR)/login
	$(RM) -- $(DESTDIR)$(BINDIR)/mktemp
	$(RM) -- $(DESTDIR)$(BINDIR)/mount
	$(RM) -- $(DESTDIR)$(BINDIR)/poweroff
	$(RM) -- $(DESTDIR)$(BINDIR)/protoid
	$(RM) -- $(DESTDIR)$(BINDIR)/reboot
	$(RM) -- $(DESTDIR)$(BINDIR)/servid
	$(RM) -- $(DESTDIR)$(BINDIR)/tar
	$(RM) -- $(DESTDIR)$(BINDIR)/umount
	$(RM) -- $(DESTDIR)$(BINDIR)/uptime
	$(RM) -- $(DESTDIR)$(BINDIR)/w

.PHONY: all clean distclean install uninstall
